name: fotonota
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.8.0
  dio: ^5.7.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  logger: ^2.2.0
  introduction_screen: ^3.1.14
  image_picker: ^1.1.2
  fl_chart: ^0.68.0
  font_awesome_flutter: ^10.7.0
  camera: ^0.11.0
  permission_handler: ^11.3.1

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo/snapcash_logo.png
  android_12:
    image: assets/images/logo/snapcash_logo.png
    icon_background_color: "#FFFFFF"
  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icons/launcher-fn.png
  adaptive_icon_background: "transparent"
  adaptive_icon_foreground: assets/images/icons/launcher-fn.png
  remove_alpha_ios: true
